### PR TITLE
Fix whitespace issues

### PR DESCRIPTION
**Pull request by vbjay**
See https://github.com/gitextensions/gitextensions/pull/6017#discussion_r244638014

### CODE REVIEW

**Comment by NoahLerner** [comment]
@vbjay 
So I just want to click on Merge pull request and my whitespace errors will be fixed? Thanks

image

**Comment by vbjay** [comment]
Do you see why it happened and how you will know if you have issues before you even push?

**Comment by NoahLerner** [comment]
To my knowledge, the reason it happened is becuase I'm using GitHub's online editor to make all my code changes. I still haven't cloned my repo locally to open it in VS. I will do that this evening, around 20:00 IST, so I can work properly.

**Comment by vbjay** [comment]
That will do it.  Yes.  Merge and it will fix your issues.

**Pull request merged**
